server:
  port: 8080

spring:
  application:
    name: order

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    schemas: orders
  jpa:
    properties:
      hibernate:
        default_schema: orders

logging:
  level:
    store: debug